export default {
    "course":{
        "lists":[
            {"text":"雅思","src":"http://media.tianxingzhe.vip/%E6%A0%BC%E5%BC%8F%E5%B7%A5%E5%8E%82%E8%8B%B1%E8%AF%AD%E9%9B%85%E6%80%9D.mp4"},
            {"text":"托福","src":"http://media.tianxingzhe.vip/%E6%A0%BC%E5%BC%8F%E5%B7%A5%E5%8E%82%E8%8B%B1%E8%AF%AD%E6%89%98%E7%A6%8F.mp4"},
            {"text":"法语","src":"http://media.tianxingzhe.vip/%E6%B3%95%E8%AF%AD"},
            {"text":"德语","src":"http://media.tianxingzhe.vip/%E5%BE%B7%E8%AF%AD"},
            {"text":"意大利","src":"http://media.tianxingzhe.vip/%E6%84%8F%E5%A4%A7%E5%88%A9%E8%AF%AD"},
            {"text":"日文","src":"http://media.tianxingzhe.vip/%E6%97%A5%E8%AF%AD"},
            {"text":"A P","src":"http://media.tianxingzhe.vip/video/AP.mp4"},
            {"text":"A L","src":"http://media.tianxingzhe.vip/video/A_Level.mp4"},
            {"text":"O L","src":"http://media.tianxingzhe.vip/video/O_A%20Level.mp4"},
  
          ]
    },
    "develop":{
        "tabs":[
            {"text":"作品集"},
            {"text":"服装设计时装秀"}
            ],
          "tabs1":[
            {"text":"全部"},
            {"text":"服装设计"},
            {"text":"平面设计"},
            {"text":"工业设计"},
            {"text":"建筑设计"},
            {"text":"插画"},
            {"text":"纯艺术"},
            ],
          "content0":[
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/chahua/f/img119.jpg",
              "name":"F同学",
              "school":"科廷大学",
              "major":"插画",
              "children": [
                {"url": "http://media.tianxingzhe.vip/develop/chahua/f/img119.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/f/img123.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/f/img129.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/f/img144.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/f/img147.jpg"},
                          ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/chahua/l/img108.jpg",
              "name":"L同学",
              "school":"澳大利亚国立大学",
              "major":"插画",
              "children":[
                {"url": "http://media.tianxingzhe.vip/develop/chahua/l/img108.jpg"},
                {"url": "http://media.tianxingzhe.vip/develop/chahua/l/img110.jpg"},
                {"url": "http://media.tianxingzhe.vip/develop/chahua/l/img116.jpg"},
                {"url": "http://media.tianxingzhe.vip/develop/chahua/l/img160.jpg"},
                {"url": "http://media.tianxingzhe.vip/develop/chahua/l/img87.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/chahua/s/img218.jpg",
              "name":"S同学",
              "school":"奥克兰大学",
              "major":"插画",
              "children":[
                {"url":"http://media.tianxingzhe.vip/develop/chahua/s/img218.jpg"},
                {"url": "http://media.tianxingzhe.vip/develop/chahua/s/img235.jpg"},
                {"url": "http://media.tianxingzhe.vip/develop/chahua/s/img238.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/s/img240.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/s/img247.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/chahua/w/img153.jpg",
              "name":"W同学",
              "school":"阿德莱德大学",
              "major":"插画",
              "children":[
                {"url":"http://media.tianxingzhe.vip/develop/chahua/w/img153.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/w/img175.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/w/img190.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/w/img194.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/w/img196.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/chahua/y/img162.jpg",
              "name":"Y同学",
              "school":"堪培拉大学",
              "major":"插画",
              "children":[
                {"url":"http://media.tianxingzhe.vip/develop/chahua/y/img162.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/y/img173.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/y/img208.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/y/img211.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/y/img212.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/chahua/z/img156.jpg",
              "name":"Z同学",
              "school":"南澳大学",
              "major":"插画",
              "children":[
                {"url":"http://media.tianxingzhe.vip/develop/chahua/z/img156.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/z/img181.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/z/img184.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/z/img187.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/z/img243.jpg"},
              ]
            },
          ],
          "content1":[
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/cloths/c/img111.jpg",
              "name":"C同学",
              "school":"科尔丁设计学院",
              "major":"服装设计",
              "children":[
                {"url": "http://media.tianxingzhe.vip/develop/cloths/c/img111.jpg"},
                {"url":   "http://media.tianxingzhe.vip/develop/cloths/c/img113.jpg"},
                {"url":   "http://media.tianxingzhe.vip/develop/cloths/c/img116.jpg"},
                {"url":  "http://media.tianxingzhe.vip/develop/cloths/c/img118.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/cloths/n/img40.jpg",
              "name":"N同学",
              "school":"蒙特利尔大学",
              "major":"服装设计",
              "children":[
                {"url":"http://media.tianxingzhe.vip/develop/cloths/n/img40.jpg"},
                {"url":  "http://media.tianxingzhe.vip/develop/cloths/n/img42.jpg"},
                {"url":  "http://media.tianxingzhe.vip/develop/cloths/n/img45.jpg"},
                {"url": "http://media.tianxingzhe.vip/develop/cloths/n/img48.jpg"},
                {"url": "http://media.tianxingzhe.vip/develop/cloths/n/img50.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/cloths/q/img85.jpg",
              "name":"Q同学",
              "school":"爱丁堡艺术学院",
              "major":"服装设计",
              "children":[
                {"url":"http://media.tianxingzhe.vip/develop/cloths/q/img85.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/cloths/q/img88.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/cloths/q/img90.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/cloths/q/img95.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/cloths/q/img90.jpg"},
                {"url":"http://p}zd0n0di.bkt.clouddn.com/develop/cloths/q/img93.jpg"}
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/cloths/w/img100.jpg",
              "name":"W同学",
              "school":"约克大学",
              "major":"服装设计",
              "children":[
                {"url":"http://media.tianxingzhe.vip/develop/cloths/w/img98.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/cloths/w/img100.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/cloths/w/img103.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/cloths/w/img105.jpg"},
                {"url": "http://media.tianxingzhe.vip/develop/cloths/w/img108.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/cloths/s/img53.jpg",
              "name":"S同学",
              "school":"维也纳应用艺术学院",
              "major":"服装设计",
              "children":[
                {"url":"http://media.tianxingzhe.vip/develop/cloths/s/img53.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/cloths/s/img55.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/cloths/s/img58.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/cloths/s/img61.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/cloths/s/img64.jpg"},
                {"url":"http://p}zd0n0di.bkt.clouddn.com/develop/cloths/s/img66.jpg"}
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/cloths/z/img69.jpg",
              "name":"Z同学",
              "school":"兰考斯特大学",
              "major":"服装设计",
              "children":[
                {"url":"http://media.tianxingzhe.vip/develop/cloths/z/img469jpg"},
                {"url": "http://media.tianxingzhe.vip/develop/cloths/z/img72.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/cloths/z/img75.jpg"},
                {"url": "http://media.tianxingzhe.vip/develop/cloths/z/img77.jpg"},
                {"url": "http://media.tianxingzhe.vip/develop/cloths/z/img83.jpg"},
              ]
            },
          ],
          "content2":[
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/plane/h/img158.jpg",
              "name":"H同学",
              "school":"宾夕法尼亚大学",
              "major":"平面设计",
              "children": [
                {"url":"http://media.tianxingzhe.vip/develop/plane/h/img158.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/plane/h/img160.jpg"},
                {"url": "http://media.tianxingzhe.vip/develop/plane/h/img171.jpg"},
                {"url": "http://media.tianxingzhe.vip/develop/plane/h/img184.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/plane/h/img195.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/plane/l/img103.jpg",
              "name":"L同学",
              "school":"杜克大学",
              "major":"平面设计",
              "children": [
              {"url":"http://media.tianxingzhe.vip/develop/plane/l/img103.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/plane/l/img109.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/plane/l/img111.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/plane/l/img113.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/plane/l/img293.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/plane/l/img293.jpg",
              "name":"L同学",
              "school":"康耐尔大学",
              "major":"平面设计",
              "children": [
              {"url":"http://media.tianxingzhe.vip/develop/plane/l/img335.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/plane/l/img346.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/plane/l/img377.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/plane/l/img391.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/plane/l/img91.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/plane/x/img472.jpg",
              "name":"X同学",
              "school":"多伦多大学",
              "major":"平面设计",
              "children": [
              {"url":"http://media.tianxingzhe.vip/develop/plane/x/img472.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/plane/x/img482.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/plane/x/img491.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/plane/x/img495.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/plane/x/img505.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/plane/y/img129.jpg",
              "name":"Y同学",
              "school":"学-萨凡纳艺术与设计学院",
              "major":"平面设计",
              "children": [
              {"url":"http://media.tianxingzhe.vip/develop/plane/y/img129.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/plane/y/img135.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/plane/y/img147.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/plane/y/img151.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/plane/y/img155.jpg"},
              ]
            },
  
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/plane/z/img70.jpg",
              "name":"Z同学",
              "school":"耶鲁大学",
              "major":"平面设计",
              "children": [
              {"url":"http://media.tianxingzhe.vip/develop/plane/z/img70.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/plane/z/img72.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/plane/z/img74.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/plane/z/img76.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/plane/z/img79.jpg"},
              ]
            },
  
          ],
          "content3":[
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/industry/c/img177.jpg",
              "name":"C同学",
              "school":"包斯豪大学",
              "major":"工业设计",
              "children": [
                {"url":"http://media.tianxingzhe.vip/develop/industry/c/img177.jpg"},
                {"url": "http://media.tianxingzhe.vip/develop/industry/c/img181.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/industry/c/img188.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/industry/c/img190.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/industry/c/img192.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/industry/d/img100.jpg",
              "name":"D同学",
              "school":"巴黎国家高等工业设计学院",
              "major":"工业设计",
              "children": [
                {"url":"http://media.tianxingzhe.vip/develop/industry/d/img100.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/industry/d/img103.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/industry/d/img109.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/industry/d/img153.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/industry/d/img97.jp}g"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/industry/f/img414.jpg",
              "name":"F同学",
              "school":"瑞典皇家美术学院",
              "major":"工业设计",
              "children": [
              {"url":"http://media.tianxingzhe.vip/develop/industry/f/img414.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/industry/f/img415.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/industry/f/img426.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/industry/f/img439.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/industry/f/img440.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/industry/q/img239.jpg",
              "name":"Q同学",
              "school":"都灵理工学院",
              "major":"工业设计",
              "children": [
              {"url":"http://media.tianxingzhe.vip/develop/industry/q/img239.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/industry/q/img241.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/industry/q/img262.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/industry/q/img268.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/industry/q/img319.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/industry/w/img348.jpg",
              "name":"W同学",
              "school":"罗马第一大学",
              "major":"工业设计",
              "children": [
              {"url":"http://media.tianxingzhe.vip/develop/industry/w/img348.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/industry/w/img352.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/industry/w/img354.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/industry/w/img355.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/industry/w/img356.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/industry/x/img385.jpg",
              "name":"X同学",
              "school":"巴萨罗纳大学",
              "major":"工业设计",
              "children": [
              {"url":"http://media.tianxingzhe.vip/develop/industry/x/img385.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/industry/x/img387.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/industry/x/img389.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/industry/x/img391.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/industry/x/img393.jpg"},
              ]
            },
          ],
          "content4":[
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/build/cEISA%20Basel,%20Javier%20Subir%C3%A1%20Ruiz..jpg",
              "name":"C同学",
              "school":"皇家墨尔本大学",
              "major":"建筑设计",
              "children": [
            {"url":"http://media.tianxingzhe.vip/develop/build/cEL%20CAMINO%20DEL%20VINO.jpg"},
                {"url": "http://media.tianxingzhe.vip/develop/build/cENTRELAZAMIENTOS.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/build/cENTRELAZAMIENTOS.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/build/cEUtopia%20Ankara.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/build/cExperimental%20Explosion.jpg"},
                  ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/build/dfichero-11461_11461.jpg",
              "name":"D同学",
              "school":"悉尼科技大学",
              "major":"建筑设计",
              "children": [
              {"url":"http://media.tianxingzhe.vip/develop/build/dfichero-11461_11461.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/build/dfichero-12142_12142.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/build/dfichero-18501_18501.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/build/dfile-44771_44771.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/build/dflesh_tanbul.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/build/fARTISTIC%20AGORA.jpg",
              "name":"F同学",
              "school":"瑞典国立艺术设计学院",
              "major":"建筑设计",
              "children": [
              {"url":"http://media.tianxingzhe.vip/develop/build/fARTISTIC%20AGORA.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/build/fArquitectura%20de%20la%20lluvia%252C%20Galer%C3%ADa%20multiprogram%C3%A1tica2.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/build/fBeirut%20Dat}a%20Platform%20-%20The%20New%20Library%20in%20Dialogue%20with%20the%20City.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/build/fBotany%20and}%20Gardening%20Center%20at%20Montjuic%20mountain.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/build/fBrotebruto.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/build/lCIAC_integreated%20center%20for%20cultural%20action.jpg",
              "name":"L同学",
              "school":"昆士兰科技大学",
              "major":"建筑设计",
              "children": [
              {"url":"http://media.tianxingzhe.vip/develop/build/lCIAC_integreated%20center%20for%20cultural%20action.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/build/lCURATIVE%20PARASITE%20_%20Urban%20Experiments.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/build/lChoreographed%20Venetian%20Epic.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/build/lDESERT%20AIR%20WELL.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/build/ldepth-of-line_11755.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/build/wfichero-11556_11556.jpg",
              "name":"W同学",
              "school":"莫纳什大学",
              "major":"建筑设计",
              "children": [
              {"url":"http://media.tianxingzhe.vip/develop/build/wfichero-1155}6_11556.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/build/wfichero-1161}7_11617.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/build/wfichero-1167}1_11671.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/build/wfichero-1169}8_11698.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/build/wfichero-1170}7_11707.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/build/xCENTER%20FOR%20MARINE%20RESEARCH%20AND%20DIFFUSION%20-%20PERU.jpg",
              "name":"X同学",
              "school":"苏黎世造型与艺术学院",
              "major":"建筑设计",
              "children": [
              {"url":"http://media.tianxingzhe.vip/develop/build/xCENTER%20FOR%20MARINE%20RESEARCH%20AND%20DIFFUSION%20-%20PERU.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/build/xCENTRO%20DE%20ARTE,%20CULTURA%20E%20IDENTIDAD%20WAYUU,%20LUIS%20ALBERTO%20MEN%C3%89NDEZ%20S%C3%81NCHEZ..jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/build/xCarlos%20A.%20Bolanos%20A..jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/build/xCentro%20Enol%C2%A2gico%20en%20La%20Portera.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/build/xbuilt_earth.jpg"},
              ]
            },
          ],
          "content5":[
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/chahua/f/img119.jpg",
              "name":"F同学",
              "school":"科廷大学",
              "major":"插画",
              "children": [
            {"url":"http://media.tianxingzhe.vip/develop/chahua/f/img119.jpg"},
                {"url": "http://media.tianxingzhe.vip/develop/chahua/f/img123.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/f/img129.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/f/img144.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/f/img147.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/chahua/l/img108.jpg",
              "name":"L同学",
              "school":"澳大利亚国立大学",
              "major":"插画",
              "children": [
              {"url":"http://media.tianxingzhe.vip/develop/chahua/l/img108.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/chahua/l/img110.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/chahua/l/img116.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/l/img160.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/l/img87.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/chahua/s/img218.jpg",
              "name":"S同学",
              "school":"奥克兰大学",
              "major":"插画",
              "children": [
              {"url":"http://media.tianxingzhe.vip/develop/chahua/s/img218.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/chahua/s/img235.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/chahua/s/img238.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/s/img240.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/s/img247.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/chahua/w/img153.jpg",
              "name":"W同学",
              "school":"阿德莱德大学",
              "major":"插画",
              "children": [
              {"url":"http://media.tianxingzhe.vip/develop/chahua/w/img153.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/chahua/w/img175.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/chahua/w/img190.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/w/img194.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/w/img196.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/chahua/y/img162.jpg",
              "name":"Y同学",
              "school":"堪培拉大学",
              "major":"插画",
              "children": [
              {"url":"http://media.tianxingzhe.vip/develop/chahua/y/img162.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/chahua/y/img173.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/chahua/y/img208.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/y/img211.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/y/img212.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/chahua/z/img156.jpg",
              "name":"Z同学",
              "school":"南澳大学",
              "major":"插画",
              "children": [
              {"url":"http://media.tianxingzhe.vip/develop/chahua/z/img156.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/chahua/z/img181.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/chahua/z/img184.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/z/img187.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/chahua/z/img243.jpg"},
              ]
            },
          ],
          "content6":[
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/yishu/c/img139.jpg",
              "name":"C同学",
              "school":"普瑞特艺术学院",
              "major":"纯艺术",
              "children": [
            {"url":"http://media.tianxingzhe.vip/develop/yishu/c/img139.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/yishu/c/img145.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/yishu/c/img148.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/yishu/c/img151.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/yishu/c/img158.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/yishu/h/img192.jpg",
              "name":"H同学",
              "school":"斯坦福大学",
              "major":"纯艺术",
              "children": [
              {"url":"http://media.tianxingzhe.vip/develop/yishu/h/img192.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/yishu/h/img195.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/yishu/h/img198.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/yishu/h/img200.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/yishu/h/img203.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/yishu/w/img100.jpg",
              "name":"W同学",
              "school":"麻省理工学院",
              "major":"纯艺术",
              "children": [
              {"url":"http://media.tianxingzhe.vip/develop/yishu/w/img100.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/yishu/w/img102.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/yishu/w/img104.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/yishu/w/img91.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/yishu/w/img94.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/yishu/x/img53.jpg",
              "name":"X同学",
              "school":"帕森设计学院",
              "major":"纯艺术",
              "children": [
              {"url":"http://media.tianxingzhe.vip/develop/yishu/x/img53.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/yishu/x/img71.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/yishu/x/img74.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/yishu/x/img84.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/yishu/x/img86.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/yishu/y/img164.jpg",
              "name":"Y同学",
              "school":"米兰理工大学",
              "major":"纯艺术",
              "children": [
              {"url":"http://media.tianxingzhe.vip/develop/yishu/y/img164.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/yishu/y/img167.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/yishu/y/img170.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/yishu/y/img173.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/yishu/y/img179.jpg"},
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/develop/yishu/z/img106.jpg",
              "name":"Z同学",
              "school":"加州艺术学院",
              "major":"纯艺术",
              "children": [
              {"url":"http://media.tianxingzhe.vip/develop/yishu/z/img106.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/yishu/z/img107.jpg"},
              {"url":"http://media.tianxingzhe.vip/develop/yishu/z/img110.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/yishu/z/img117.jpg"},
                {"url":"http://media.tianxingzhe.vip/develop/yishu/z/img123.jpg"},
              ]
            },
          ],
          "content21":[
            {
              "imgSrc":"http://media.tianxingzhe.vip/fu/fu1.jpg",
              "name":"毕业时装秀",
              "school":"伦敦大学",
              "major":"服装设计专业",
              "children":[
                "http://media.tianxingzhe.vip/%E6%A0%BC%E5%BC%8F%E5%B7%A5%E5%8E%82%E4%BC%A6%E6%95%A6%E5%A4%A7%E5%AD%A6%E6%9C%8D%E8%A3%85%E8%AE%BE%E8%AE%A1%E4%B8%93%E4%B8%9A%E6%AF%95%E4%B8%9A%E6%97%B6%E8%A3%85%E7%A7%802.mp4",
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/fu/fu2.jpg",
              "name":"服装设计时装秀",
              "school":"加拿大预科",
              "major":"服装设计专业",
              "children":[
                "http://media.tianxingzhe.vip/%E6%A0%BC%E5%BC%8F%E5%B7%A5%E5%8E%82%E5%8A%A0%E6%8B%BF%E5%A4%A7%E9%A2%84%E7%A7%91%E6%9C%8D%E8%A3%85%E8%AE%BE%E8%AE%A1%E6%97%B6%E8%A3%85%E7%A7%802.mp4",
              ]
            },
            {
              "imgSrc":"http://media.tianxingzhe.vip/fu/fu3.jpg",
              "name":"毕业时装秀",
              "school":"英国剑桥大学",
              "major":"服装设计专业",
              "children":[
                "http://media.tianxingzhe.vip/%E6%A0%BC%E5%BC%8F%E5%B7%A5%E5%8E%82%E8%8B%B1%E5%9B%BD%E5%89%91%E6%A1%A5%E5%A4%A7%E5%AD%A6%E6%9C%8D%E8%A3%85%E8%AE%BE%E8%AE%A1%E6%AF%95%E4%B8%9A%E6%97%B6%E8%A3%85%E7%A7%802.mp4",
              ]
            },
          ],
  
    },
    "template":{
        "tabContents":[
            {
                "content": [
                {
                    "campus":"美国专业",
                    "children":[
                    {
                        "text":"历史学",
                        "url":"http://media.tianxingzhe.vip/template/%E7%95%99%E5%AD%A6%E6%96%87%E4%B9%A6%E4%B8%AA%E4%BA%BA%E9%99%88%E8%BF%B0%E8%8C%83%E6%96%87%EF%BC%9A%E5%8E%86%E5%8F%B2%E5%AD%A6.pdf",
                    },
                    {
                        "text":"电器工程",
                        "url":"http://media.tianxingzhe.vip/template/%E7%94%B5%E5%99%A8%E5%B7%A5%E7%A8%8B%E4%B8%93%E4%B8%9A%E4%B8%AA%E4%BA%BA%E9%99%88%E8%BF%B0%E8%8C%83%E6%96%87.pdf",
                    },
                    {
                        "text":"数学专业",
                        "url":"http://media.tianxingzhe.vip/template/%E6%95%B0%E5%AD%A6%E4%B8%93%E4%B8%9A%E4%B8%AA%E4%BA%BA%E9%99%88%E8%BF%B0%E8%8C%83%E6%96%87.pdf",
                    },
                    ]
                },
                {
                    "campus":"英国",
                    "children":[
                    {
                        "text":"软件工程",
                        "url":"http://media.tianxingzhe.vip/template/%E7%95%99%E5%AD%A6%E6%96%87%E4%B9%A6%E4%B8%AA%E4%BA%BA%E9%99%88%E8%BF%B0%E8%8C%83%E6%96%87%EF%BC%9A%E8%BD%AF%E4%BB%B6%E5%B7%A5%E7%A8%8B.pdf",
                    },
                    {
                        "text":"生物医学",
                        "url":"http://media.tianxingzhe.vip/template/%E4%B8%AA%E4%BA%BA%E9%99%88%E8%BF%B0%E8%8C%83%E6%96%87%E7%94%9F%E7%89%A9%E5%8C%BB%E5%AD%A6.pdf",
                    },
                    {
                        "text":"地理学",
                        "url":"http://media.tianxingzhe.vip/template/%E7%95%99%E5%AD%A6%E6%96%87%E4%B9%A6%E4%B8%AA%E4%BA%BA%E9%99%88%E8%BF%B0%E8%8C%83%E6%96%87%EF%BC%9A%E5%9C%B0%E7%90%86%E5%AD%A6.pdf",
                    },
                    ]
                },
                {
                    "campus":"英国",
                    "children":[
                    {
                        "text":"建筑专业",
                        "url":"http://media.tianxingzhe.vip/template/%E4%B8%AA%E4%BA%BA%E9%99%88%E8%BF%B0%E8%8C%83%E4%BE%8B%E2%80%94%E2%80%94%E5%BB%BA%E7%AD%91%E4%B8%93%E4%B8%9A.pdf",
                    },
                    {
                        "text":"牙医专业",
                        "url":"http://media.tianxingzhe.vip/template/%E7%89%99%E5%8C%BB%E4%B8%93%E4%B8%9A%E4%B8%AA%E4%BA%BA%E9%99%88%E8%BF%B0%E8%8C%83%E6%96%87.pdf",
                    },
                    {
                        "text":"人类学",
                        "url":"http://media.tianxingzhe.vip/template/%E7%95%99%E5%AD%A6%E6%96%87%E4%B9%A6%E4%B8%AA%E4%BA%BA%E9%99%88%E8%BF%B0%E8%8C%83%E6%96%87%EF%BC%9A%E4%BA%BA%E7%B1%BB%E5%AD%A6.pdf",
                    },
                    ]
                },
                {
                    "campus":"英国",
                    "children":[
                    {
                        "text":"生物化学",
                        "url":"http://media.tianxingzhe.vip/template/%E7%95%99%E5%AD%A6%E6%96%87%E4%B9%A6%E4%B8%AA%E4%BA%BA%E9%99%88%E8%BF%B0%E8%8C%83%E6%96%87%EF%BC%9A%E7%94%9F%E7%89%A9%E5%8C%96%E5%AD%A6.pdf",
                    },
                    {
                        "text":"政治学",
                        "url":"http://media.tianxingzhe.vip/template/%E7%95%99%E5%AD%A6%E6%96%87%E4%B9%A6%E4%B8%AA%E4%BA%BA%E9%99%88%E8%BF%B0%E8%8C%83%E6%96%87%EF%BC%9A%E6%94%BF%E6%B2%BB%E5%AD%A6.pdf",
                    },
                    {
                        "text":"法律专业",
                        "url":"http://media.tianxingzhe.vip/template/%E7%94%B3%E8%AF%B7%E6%96%87%E4%B9%A6%EF%BC%9A%E6%B3%95%E5%BE%8B%E4%B8%93%E4%B8%9A%E4%B8%AA%E4%BA%BA%E9%99%88%E8%BF%B0%E8%8C%83%E6%96%87.pdf",
                    },
                    ]
                },
                {
                    "campus":"英国",
                    "children":[
                    {
                        "text":"材料科学",
                        "url":"http://media.tianxingzhe.vip/template/%E4%B8%AA%E4%BA%BA%E9%99%88%E8%BF%B0%E8%8C%83%E6%96%87%E2%80%94%E2%80%94%E6%9D%90%E6%96%99%E7%A7%91%E5%AD%A6.pdf",
                    },
                    {
                        "text":"戏剧学",
                        "url":"http://media.tianxingzhe.vip/template/%E7%95%99%E5%AD%A6%E6%96%87%E4%B9%A6%E4%B8%AA%E4%BA%BA%E9%99%88%E8%BF%B0%E8%8C%83%E6%96%87%EF%BC%9A%E6%88%8F%E5%89%A7.pdf",
                    },
                    {
                        "text":"艺术设计",
                        "url":"http://media.tianxingzhe.vip/template/%E8%89%BA%E6%9C%AF%E8%AE%BE%E8%AE%A1%E4%B8%93%E4%B8%9A%E4%B8%AA%E4%BA%BA%E9%99%88%E8%BF%B0%E8%8C%83%E6%96%87.pdf",
                    },
                    ]
                },
                {
                    "campus":"英国",
                    "children":[
                    {
                        "text":"广告策划",
                        "url":"http://media.tianxingzhe.vip/template/%E7%95%99%E5%AD%A6%E6%96%87%E4%B9%A6%E4%B8%AA%E4%BA%BA%E9%99%88%E8%BF%B0%E8%8C%83%E6%96%87%EF%BC%9A%E5%B9%BF%E5%91%8A%E7%AD%96%E5%88%92.pdf",
                    },
                    {
                        "text":"航空航天",
                        "url":"http://media.tianxingzhe.vip/template/%E7%95%99%E5%AD%A6%E6%96%87%E4%B9%A6%E4%B8%AA%E4%BA%BA%E9%99%88%E8%BF%B0%E8%8C%83%E6%96%87%EF%BC%9A%E8%88%AA%E7%A9%BA%E8%88%AA%E5%A4%A9.pdf",
                    },
                    {
                        "text":"金融经济",
                        "url":"http://media.tianxingzhe.vip/template/%E7%95%99%E5%AD%A6%E4%B8%AA%E4%BA%BA%E9%99%88%E8%BF%B0%E8%8C%83%E6%96%87%E2%80%94%E2%80%94%E9%87%91%E8%9E%8D%E7%BB%8F%E6%B5%8E%E7%B1%BB.pdf",
                    },
                    ]
                },
                ]
            },
            {
                "content": [
                {
                    "campus":"美国的",
                    "children":[
                    {
                        "text":"杜克大学",
                        "url":"http://media.tianxingzhe.vip/template/Duke+Resume+Template.pdf",
                    },
                    {
                        "text":"耶鲁大学",
                        "url":"http://media.tianxingzhe.vip/template/Yale%20resume%20tips.pdf",
                    },
                    {
                        "text":"康奈尔大学",
                        "url":"http://media.tianxingzhe.vip/template/Cornell%20resume%20template.pdf",
                    },
                    ]
                },
                {
                    "campus":"英国的",
                    "children":[
                    {
                        "text":"哥伦比亚大学",
                        "url":"http://media.tianxingzhe.vip/template/Columbia%20resume%20sample%20sample+resume+in+MC.pdf",
                    },
                    {
                        "text":"耶鲁大学",
                        "url":"http://media.tianxingzhe.vip/template/Dupras-Boileau_Laurent_CV.pdf",
                    },
                    {
                        "text":"普林斯顿大学",
                        "url":"http://media.tianxingzhe.vip/template/Fischer_Jeremie_CV.pdf",
                    },
                    ]
                },
                {
                    "campus":"英国的",
                    "children":[
                    {
                        "text":"剑桥大学",
                        "url":"http://media.tianxingzhe.vip/template/hbs2001resumes.pdf",
                    },
                    {
                        "text":"普林斯顿大学",
                        "url":"http://media.tianxingzhe.vip/template/Wu_Tong_CV.pdf",
                    },
                    {
                        "text":"普林斯顿大学",
                        "url":"http://media.tianxingzhe.vip/template/Zabukovec_Igor_CV.pdf",
                    },
                    ]
                },
                {
                    "campus":"英国的",
                    "children":[
                    {
                        "text":"商行",
                        "url":"http://media.tianxingzhe.vip/template/work/%E5%95%86%E8%A1%8C1.pdf",
                    },
                    {
                        "text":"投行",
                        "url":"http://media.tianxingzhe.vip/template/work/%E6%8A%95%E8%A1%8C1.pdf",
                    },
                    {
                        "text":"券商",
                        "url":"http://media.tianxingzhe.vip/template/work/%E5%88%B8%E5%95%861.pdf",
                    }
                    ]
                },
                {
                    "campus":"英国的",
                    "children":[
                    {
                        "text":"人力咨询",
                        "url":"http://media.tianxingzhe.vip/template/work/%E4%BA%BA%E5%8A%9B%E5%92%A8%E8%AF%A21.pdf",
                    },
                    {
                        "text":"管理咨询",
                        "url":"http://media.tianxingzhe.vip/template/work/%E7%AE%A1%E7%90%86%E5%92%A8%E8%AF%A23.pdf",
                    },
                    {
                        "text":"律师事务所",
                        "url":"http://media.tianxingzhe.vip/template/work/%E5%9B%9B%E5%A4%A71.pdf",
                    }
                    ]
                },
                {
                    "campus":"英国的",
                    "children":[
                    {
                        "text":"互联网",
                        "url":"http://media.tianxingzhe.vip/template/work/%E4%BA%92%E8%81%94%E7%BD%911.pdf",
                    },
                    {
                        "text":"人力资源",
                        "url":"http://media.tianxingzhe.vip/template/work/%E4%BA%BA%E5%8A%9B%E8%B5%84%E6%BA%901.pdf",
                    },
                    {
                        "text":"保险",
                        "url":"http://media.tianxingzhe.vip/template/work/%E4%BF%9D%E9%99%A91.pdf",
                    }
                    ]
                },
                {
                    "campus":"英国的",
                    "children":[
                    {
                        "text":"外贸",
                        "url":"http://media.tianxingzhe.vip/template/work/%E5%A4%96%E8%B4%B81.pdf",
                    },
                    {
                        "text":"物流",
                        "url":"http://media.tianxingzhe.vip/template/work/%E7%89%A9%E6%B5%811.pdf",
                    },
                    {
                        "text":"法律",
                        "url":"http://media.tianxingzhe.vip/template/work/%E6%B3%95%E5%BE%8B1.pdf",
                    }
                    ]
                },
                ]
            },
            {
                "content": [
                {
                    "campus":"美国的",
                    "children":[
                    {
                        "text":"成功申请哈佛的Essay范文",
                        "url":"http://media.tianxingzhe.vip/video/%E6%8E%A8%E8%8D%90%E4%BF%A1Andrew%20Rist%E6%88%90%E5%8A%9F%E7%94%B3%E8%AF%B7%E5%93%88%E4%BD%9B%E7%9A%84Essay%E8%8C%83%E6%96%87.pdf",
                    },
                    {
                        "text":"Dartmouth College",
                        "url":"http://media.tianxingzhe.vip/video/%E6%8E%A8%E8%8D%90%E4%BF%A1Dartmouth%20College.pdf",
                    },
                    {
                        "text":"Essay Four",
                        "url":"http://media.tianxingzhe.vip/video/%E6%8E%A8%E8%8D%90%E4%BF%A1Essay%20Four.pdf",
                    },
                    ]
                },
                {
                    "campus":"英国的",
                    "children":[
                    {
                        "text":"Essay One",
                        "url":"http://media.tianxingzhe.vip/video/%E6%8E%A8%E8%8D%90%E4%BF%A1Essay%20One.pdf",
                    },
                    {
                        "text":"Essay Two",
                        "url":"http://media.tianxingzhe.vip/video/%E6%8E%A8%E8%8D%90%E4%BF%A1Essay%20Two.pdf",
                    },
                    {
                        "text":"Essay Three",
                        "url":"http://media.tianxingzhe.vip/video/%E6%8E%A8%E8%8D%90%E4%BF%A1Essay%20Three.pdf",
                    },
                    ]
                },
                {
                    "campus":"英国的",
                    "children":[
                    {
                        "text":"Macalester College",
                        "url":"http://media.tianxingzhe.vip/video/%E6%8E%A8%E8%8D%90%E4%BF%A1Macalester%20College.pdf",
                    },
                    {
                        "text":"Oberlin College",
                        "url":"http://media.tianxingzhe.vip/video/%E6%8E%A8%E8%8D%90%E4%BF%A1Oberlin%20College.pdf",
                    },
                    {
                        "text":"Tufts University",
                        "url":"http://media.tianxingzhe.vip/video/%E6%8E%A8%E8%8D%90%E4%BF%A1Tufts%20University.pdf",
                    },
                    ]
                },
                {
                    "campus":"英国的",
                    "children":[
                    {
                        "text":"University of Chicago",
                        "url":"http://media.tianxingzhe.vip/video/%E6%8E%A8%E8%8D%90%E4%BF%A1University%20of%20Chicago.pdf",
                    },
                    {
                        "text":"new essay01",
                        "url":"http://media.tianxingzhe.vip/video/%E6%8E%A8%E8%8D%90%E4%BF%A1new%20essay01.pdf",
                    },
                    {
                        "text":"new essay02",
                        "url":"http://media.tianxingzhe.vip/video/%E6%8E%A8%E8%8D%90%E4%BF%A1new%20essay02.pdf",
                    },
                    ]
                },
                {
                    "campus":"英国的",
                    "children":[
                    {
                        "text":"new essay03",
                        "url":"http://media.tianxingzhe.vip/video/%E6%8E%A8%E8%8D%90%E4%BF%A1new%20essay03.pdf",
                    },
                    {
                        "text":"new essay04",
                        "url":"http://media.tianxingzhe.vip/video/%E6%8E%A8%E8%8D%90%E4%BF%A1new%20essay04.pdf",
                    },
                    {
                        "text":"乔治亚理工学院",
                        "url":"http://media.tianxingzhe.vip/video/%E6%8E%A8%E8%8D%90%E4%BF%A1%E4%B9%94%E6%B2%BB%E4%BA%9A%E7%90%86%E5%B7%A5%E5%AD%A6%E9%99%A2.pdf",
                    },
                    ]
                },
                {
                    "campus":"英国的",
                    "children":[
                    {
                        "text":"华盛顿州立大学",
                        "url":"http://media.tianxingzhe.vip/video/%E6%8E%A8%E8%8D%90%E4%BF%A1%E5%8D%8E%E7%9B%9B%E9%A1%BF%E5%B7%9E%E7%AB%8B%E5%A4%A7%E5%AD%A6.pdf",
                    },
                    {
                        "text":"哈佛大学",
                        "url":"http://media.tianxingzhe.vip/video/%E6%8E%A8%E8%8D%90%E4%BF%A1%E5%93%88%E4%BD%9B%E5%A4%A7%E5%AD%A6%202.pdf",
                    },
                    {
                        "text":"宾夕法尼亚大学",
                        "url":"http://media.tianxingzhe.vip/video/%E6%8E%A8%E8%8D%90%E4%BF%A1%E5%AE%BE%E5%A4%95%E6%B3%95%E5%B0%BC%E4%BA%9A%E5%A4%A7%E5%AD%A6.pdf",
                    },
                    ]
                },
                {
                    "campus":"英国的",
                    "children":[
                    {
                        "text":"斯沃斯莫尔学院",
                        "url":"http://media.tianxingzhe.vip/video/%E6%8E%A8%E8%8D%90%E4%BF%A1%E6%96%AF%E6%B2%83%E6%96%AF%E8%8E%AB%E5%B0%94%E5%AD%A6%E9%99%A2.pdf",
                    },
                    {
                        "text":"普林斯顿大学",
                        "url":"http://media.tianxingzhe.vip/video/%E6%8E%A8%E8%8D%90%E4%BF%A1%E6%99%AE%E6%9E%97%E6%96%AF%E9%A1%BF%E5%A4%A7%E5%AD%A6.pdf",
                    },
                    {
                        "text":"曼荷莲女子学院",
                        "url":"http://media.tianxingzhe.vip/video/%E6%8E%A8%E8%8D%90%E4%BF%A1%E6%9B%BC%E8%8D%B7%E8%8E%B2%E5%A5%B3%E5%AD%90%E5%AD%A6%E9%99%A2.pdf",
                    },
                    ]
                },
                {
                    "campus":"英国的",
                    "children":[
                    {
                        "text":"杜克大学",
                        "url":"http://media.tianxingzhe.vip/video/%E6%8E%A8%E8%8D%90%E4%BF%A1%E6%9D%9C%E5%85%8B%E5%A4%A7%E5%AD%A6.pdf",
                    },
                    {
                        "text":"耶鲁大学",
                        "url":"http://media.tianxingzhe.vip/video/%E6%8E%A8%E8%8D%90%E4%BF%A1%E8%80%B6%E9%B2%81%E5%A4%A7%E5%AD%A6.pdf",
                    },
                    {
                        "text":"芝加哥大学",
                        "url":"http://media.tianxingzhe.vip/video/%E6%8E%A8%E8%8D%90%E4%BF%A1%E8%8A%9D%E5%8A%A0%E5%93%A5%E5%A4%A7%E5%AD%A6.pdf",
                    },
                    ]
                },
                ]
            },
            {
                "content": [
                {
                    "campus":"美国的",
                    "children":[
                    {
                        "text":"套磁1",
                        "url":"http://media.tianxingzhe.vip/video/%E5%A5%97%E7%A3%81%E4%BF%A1%E5%A5%97%E7%A3%81%20%281%29.pdf",
                    },
                    {
                        "text":"套磁2",
                        "url":"http://media.tianxingzhe.vip/video/%E5%A5%97%E7%A3%81%E4%BF%A1%E5%A5%97%E7%A3%81%20%282%29.pdf",
                    },
                    {
                        "text":"套磁3",
                        "url":"http://media.tianxingzhe.vip/video/%E5%A5%97%E7%A3%81%E4%BF%A1%E5%A5%97%E7%A3%81%20%283%29.pdf",
                    },
                    ]
                },
                {
                    "campus":"美国的",
                    "children":[
                    {
                        "text":"套磁4",
                        "url":"http://media.tianxingzhe.vip/video/%E5%A5%97%E7%A3%81%E4%BF%A1%E5%A5%97%E7%A3%81%20%284%29.pdf",
                    },
                    {
                        "text":"套磁5",
                        "url":"http://media.tianxingzhe.vip/video/%E5%A5%97%E7%A3%81%E4%BF%A1%E5%A5%97%E7%A3%81%20%285%29.pdf",
                    },
                    {
                        "text":"套磁6",
                        "url":"http://media.tianxingzhe.vip/video/%E5%A5%97%E7%A3%81%E4%BF%A1%E5%A5%97%E7%A3%81%20%286%29.pdf",
                    },
                    ]
                },
                {
                    "campus":"美国的",
                    "children":[
                    {
                        "text":"套磁7",
                        "url":"http://media.tianxingzhe.vip/video/%E5%A5%97%E7%A3%81%E4%BF%A1%E5%A5%97%E7%A3%81%20%287%29.pdf",
                    },
                    {
                        "text":"套磁8",
                        "url":"http://media.tianxingzhe.vip/video/%E5%A5%97%E7%A3%81%E4%BF%A1%E5%A5%97%E7%A3%81%20%288%29.pdf",
                    },
                    {
                        "text":"套磁9",
                        "url":"http://media.tianxingzhe.vip/video/%E5%A5%97%E7%A3%81%E4%BF%A1%E5%A5%97%E7%A3%81%20%289%29.pdf",
                    },
                    ]
                },
                {
                    "campus":"美国的",
                    "children":[
                    {
                        "text":"套磁10",
                        "url":"http://media.tianxingzhe.vip/video/%E5%A5%97%E7%A3%81%E4%BF%A1%E5%A5%97%E7%A3%81%20%2810%29.pdf",
                    },
                    {
                        "text":"套磁11",
                        "url":"http://media.tianxingzhe.vip/video/%E5%A5%97%E7%A3%81%E4%BF%A1%E5%A5%97%E7%A3%81%20%2811%29.pdf",
                    },
                    {
                        "text":"套磁12",
                        "url":"http://media.tianxingzhe.vip/video/%E5%A5%97%E7%A3%81%E4%BF%A1%E5%A5%97%E7%A3%81%20%2812%29.pdf",
                    },
                    ]
                },
                {
                    "campus":"美国的",
                    "children":[
                    {
                        "text":"套磁13",
                        "url":"http://media.tianxingzhe.vip/video/%E5%A5%97%E7%A3%81%E4%BF%A1%E5%A5%97%E7%A3%81%20%2813%29.pdf",
                    },
                    {
                        "text":"套磁14",
                        "url":"http://media.tianxingzhe.vip/video/%E5%A5%97%E7%A3%81%E4%BF%A1%E5%A5%97%E7%A3%81%20%2814%29.pdf",
                    },
                    {
                        "text":"套磁15",
                        "url":"http://media.tianxingzhe.vip/video/%E5%A5%97%E7%A3%81%E4%BF%A1%E5%A5%97%E7%A3%81%20%2815%29.pdf",
                    },
                    ]
                },
                {
                    "campus":"美国的",
                    "children":[
                    {
                        "text":"套磁16",
                        "url":"http://media.tianxingzhe.vip/video/%E5%A5%97%E7%A3%81%E4%BF%A1%E5%A5%97%E7%A3%81%20%2816%29.pdf",
                    },
                    {
                        "text":"套磁17",
                        "url":"http://media.tianxingzhe.vip/video/%E5%A5%97%E7%A3%81%E4%BF%A1%E5%A5%97%E7%A3%81%20%2817%29.pdf",
                    },
                    {
                        "text":"套磁18",
                        "url":"http://media.tianxingzhe.vip/video/%E5%A5%97%E7%A3%81%E4%BF%A1%E5%A5%97%E7%A3%81%20%2818%29.pdf",
                    },
                    ]
                },
                {
                    "campus":"美国的",
                    "children":[
                    {
                        "text":"套磁19",
                        "url":"http://media.tianxingzhe.vip/video/%E5%A5%97%E7%A3%81%E4%BF%A1%E5%A5%97%E7%A3%81%20%2819%29.pdf",
                    },
                    {
                        "text":"套磁20",
                        "url":"http://media.tianxingzhe.vip/video/%E5%A5%97%E7%A3%81%E4%BF%A1%E5%A5%97%E7%A3%81%20%2820%29.pdf",
                    },
                    {
                        "text":"套磁21",
                        "url":"http://media.tianxingzhe.vip/video/%E5%A5%97%E7%A3%81%E4%BF%A1%E5%A5%97%E7%A3%81%20%2821%29.pdf",
                    },
                    ]
                },

                ]
            },
        ],
        "tabs": ["申请文书", "简历模板","推荐信","套磁信"]
    },
    "video":{
        "cityList": [
            {
              value: 'a',
              label: '加拿大大学'
            },
            {
              value: 'b',
              label: '英国大学'
            },
            {
              value: 'c',
              label: '法国大学'
            },
            {
              value: 'd',
              label: '美国大学'
            },
            {
              value: 'e',
              label: '德国大学'
            },
            {
              value: 'f',
              label: '意大利大学'
            },
            {
              value: 'g',
              label: '新加坡大学'
            },
            {
              value: 'h',
              label: '新西兰大学'
            },
            {
              value: 'i',
              label: '澳洲大学'
            },
            {
              value: 'j',
              label: '西班牙大学'
            },
            {
              value: 'k',
              label: '香港大学'
            },
            {
              value: 'l',
              label: '荷兰大学'
            },
          ],
        "lists":{
            'a':[
              {"id":1,"imgSrc":"http://media.tianxingzhe.vip/video/%E5%8A%A0%E6%8B%BF%E5%A4%A7%E5%A4%9A%E4%BC%A6%E5%A4%9A%E5%A4%A7%E5%AD%A6.jpg","text":"多伦多大学","videoSrc":"http://media.tianxingzhe.vip/video/%E5%8A%A0%E6%8B%BF%E5%A4%A7%E5%A4%9A%E4%BC%A6%E5%A4%9A%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":2,"imgSrc":"http://media.tianxingzhe.vip/video/%E5%8A%A0%E6%8B%BF%E5%A4%A7%E5%B8%83%E9%B2%81%E5%85%8B%E5%A4%A7%E5%AD%A6.jpg","text":"布鲁克大学","videoSrc":"http://media.tianxingzhe.vip/video/%E5%8A%A0%E6%8B%BF%E5%A4%A7%E5%B8%83%E9%B2%81%E5%85%8B%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":3,"imgSrc":"http://media.tianxingzhe.vip/video/%E5%8A%A0%E6%8B%BF%E5%A4%A7%E6%B8%A5%E5%A4%AA%E5%8D%8E%E5%A4%A7%E5%AD%A6.jpg","text":"渥太华大学","videoSrc":"http://media.tianxingzhe.vip/video/%E5%8A%A0%E6%8B%BF%E5%A4%A7%E6%B8%A5%E5%A4%AA%E5%8D%8E%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":4,"imgSrc":"http://media.tianxingzhe.vip/video/%E5%8A%A0%E6%8B%BF%E5%A4%A7%E6%BB%91%E9%93%81%E5%8D%A2%E5%A4%A7%E5%AD%A6.jpg","text":"滑铁卢大学","videoSrc":"http://media.tianxingzhe.vip/video/%E5%8A%A0%E6%8B%BF%E5%A4%A7%E6%BB%91%E9%93%81%E5%8D%A2%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":5,"imgSrc":"http://media.tianxingzhe.vip/video/%E5%8A%A0%E6%8B%BF%E5%A4%A7%E7%BA%A6%E5%85%8B%E5%A4%A7%E5%AD%A6.jpg","text":"约克大学","videoSrc":"http://media.tianxingzhe.vip/video/%E5%8A%A0%E6%8B%BF%E5%A4%A7%E7%BA%A6%E5%85%8B%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":6,"imgSrc":"http://media.tianxingzhe.vip/video/%E5%8A%A0%E6%8B%BF%E5%A4%A7%E7%BB%B4%E5%A4%9A%E5%88%A9%E4%BA%9A%E5%A4%A7%E5%AD%A6.jpg","text":"维多利亚大学","videoSrc":"http://media.tianxingzhe.vip/video/%E5%8A%A0%E6%8B%BF%E5%A4%A7%E7%BB%B4%E5%A4%9A%E5%88%A9%E4%BA%9A%E5%A4%A7%E5%AD%A64.mp4"},
              {"id":7,"imgSrc":"http://media.tianxingzhe.vip/video/%E5%8A%A0%E6%8B%BF%E5%A4%A7%E8%92%99%E7%89%B9%E5%88%A9%E5%B0%94%E5%A4%A7%E5%AD%A6.jpg","text":"蒙特利尔大学","videoSrc":"http://media.tianxingzhe.vip/video/%E5%8A%A0%E6%8B%BF%E5%A4%A7%E8%92%99%E7%89%B9%E5%88%A9%E5%B0%94%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":8,"imgSrc":"http://media.tianxingzhe.vip/video/%E5%8A%A0%E6%8B%BF%E5%A4%A7%E9%98%BF%E5%B0%94%E4%BC%AF%E5%A1%94%E5%A4%A7%E5%AD%A6.jpg","text":"阿尔伯塔大学","videoSrc":"http://media.tianxingzhe.vip/video/%E5%8A%A0%E6%8B%BF%E5%A4%A7%E9%98%BF%E5%B0%94%E4%BC%AF%E5%A1%94%E5%A4%A7%E5%AD%A6.mp4"},
            ],
            'b':[
              {"id":1,"imgSrc":"http://media.tianxingzhe.vip/video/%E8%8B%B1%E5%9B%BD%E4%BC%A6%E6%95%A6%E5%A4%A7%E5%AD%A6.jpg","text":"伦敦大学","videoSrc":"http://media.tianxingzhe.vip/video/%E8%8B%B1%E5%9B%BD%E4%BC%A6%E6%95%A6%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":2,"imgSrc":"http://media.tianxingzhe.vip/video/%E8%8B%B1%E5%9B%BD%E4%BC%A6%E6%95%A6%E6%94%BF%E6%B2%BB%E7%BB%8F%E6%B5%8E%E5%AD%A6%E9%99%A2.jpg","text":"伦敦政治经济学院","videoSrc":"http://media.tianxingzhe.vip/video/%E8%8B%B1%E5%9B%BD%E4%BC%A6%E6%95%A6%E6%94%BF%E6%B2%BB%E7%BB%8F%E6%B5%8E%E5%AD%A6%E9%99%A2.mp4"},
              {"id":3,"imgSrc":"http://media.tianxingzhe.vip/video/%E8%8B%B1%E5%9B%BD%E5%85%B0%E8%80%83%E6%96%AF%E7%89%B9%E5%A4%A7%E5%AD%A6.jpg","text":"兰考斯特大学","videoSrc":"http://media.tianxingzhe.vip/video/%E8%8B%B1%E5%9B%BD%E5%85%B0%E8%80%83%E6%96%AF%E7%89%B9%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":4,"imgSrc":"http://media.tianxingzhe.vip/video/%E8%8B%B1%E5%9B%BD%E5%89%91%E6%A1%A5%E5%A4%A7%E5%AD%A6.jpg","text":"剑桥大学","videoSrc":"http://media.tianxingzhe.vip/video/%E8%8B%B1%E5%9B%BD%E5%89%91%E6%A1%A5%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":5,"imgSrc":"http://media.tianxingzhe.vip/video/%E8%8B%B1%E5%9B%BD%E5%9C%A3%E5%AE%89%E5%BE%B7%E9%B2%81%E6%96%AF%E5%A4%A7%E5%AD%A6.jpg","text":"安德鲁斯大学","videoSrc":"http://media.tianxingzhe.vip/video/%E8%8B%B1%E5%9B%BD%E5%9C%A3%E5%AE%89%E5%BE%B7%E9%B2%81%E6%96%AF%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":6,"imgSrc":"http://media.tianxingzhe.vip/video/%E8%8B%B1%E5%9B%BD%E6%9D%9C%E4%BC%A6%E5%A4%A7%E5%AD%A6.jpg","text":"杜伦大学","videoSrc":"http://media.tianxingzhe.vip/video/%E8%8B%B1%E5%9B%BD%E6%9D%9C%E4%BC%A6%E5%A4%A7%E5%AD%A6.mp4"},
            ],
            'c':[
              {"id":1,"imgSrc":"http://media.tianxingzhe.vip/video/%E6%B3%95%E5%9B%BD%E4%B8%AD%E5%A4%AE%E7%90%86%E5%B7%A5%E5%AD%A6%E9%99%A2.jpg","text":"中央理工学院","videoSrc":"http://media.tianxingzhe.vip/video/%E6%B3%95%E5%9B%BD%E4%B8%AD%E5%A4%AE%E7%90%86%E5%B7%A5%E5%AD%A6%E9%99%A2.mp4"},
              {"id":2,"imgSrc":"http://media.tianxingzhe.vip/video/%E6%B3%95%E5%9B%BD%E5%B7%B4%E9%BB%8E%E6%94%BF%E6%B2%BB%E5%AD%A6%E9%99%A2.jpg","text":"巴黎政治学院","videoSrc":"http://media.tianxingzhe.vip/video/%E6%B3%95%E5%9B%BD%E5%B7%B4%E9%BB%8E%E6%94%BF%E6%B2%BB%E5%AD%A6%E9%99%A2.mp4"},
              {"id":3,"imgSrc":"http://media.tianxingzhe.vip/video/%E6%B3%95%E5%9B%BD%E5%B7%B4%E9%BB%8E%E7%AC%AC%E4%B8%80%E5%A4%A7%E5%AD%A6.jpg","text":"巴黎第一大学","videoSrc":"http://media.tianxingzhe.vip/video/%E6%B3%95%E5%9B%BD%E5%B7%B4%E9%BB%8E%E7%AC%AC%E4%B8%80%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":4,"imgSrc":"http://media.tianxingzhe.vip/video/%E6%B3%95%E5%9B%BD%E6%A0%BC%E5%8B%92%E8%AF%BA%E5%B8%83%E5%B0%94%E5%A4%A7%E5%AD%A6.jpg","text":"格勒诺布尔大学","videoSrc":"http://media.tianxingzhe.vip/video/%E6%B3%95%E5%9B%BD%E6%A0%BC%E5%8B%92%E8%AF%BA%E5%B8%83%E5%B0%94%E5%A4%A7%E5%AD%A6.mp4"},
            ],
            'd':[
              {"id":1,"imgSrc":"http://media.tianxingzhe.vip/video/%E7%BE%8E%E5%9B%BD%E4%BF%84%E5%8B%92%E5%86%88%E5%A4%A7%E5%AD%A6.jpg","text":"俄勒冈大学","videoSrc":"http://media.tianxingzhe.vip/video/%E7%BE%8E%E5%9B%BD%E4%BF%84%E5%8B%92%E5%86%88%E5%A4%A7%E5%AD%A61Ryan%20L.mp4"},
              {"id":2,"imgSrc":"http://media.tianxingzhe.vip/video/%E7%BE%8E%E5%9B%BD%E6%96%AF%E5%9D%A6%E7%A6%8F%E5%A4%A7%E5%AD%A6.jpg","text":"斯坦福大学","videoSrc":"http://media.tianxingzhe.vip/video/%E7%BE%8E%E5%9B%BD%E6%96%AF%E5%9D%A6%E7%A6%8F%E5%A4%A7%E5%AD%A61.mp4"},
              {"id":3,"imgSrc":"http://media.tianxingzhe.vip/video/%E7%BE%8E%E5%9B%BD%E6%99%AE%E6%9E%97%E6%96%AF%E9%A1%BF%E5%A4%A7%E5%AD%A6.jpg","text":"普林斯顿大学","videoSrc":"http://media.tianxingzhe.vip/video/%E7%BE%8E%E5%9B%BD%E6%99%AE%E6%9E%97%E6%96%AF%E9%A1%BF%E5%A4%A7%E5%AD%A61.mp4"},
              {"id":4,"imgSrc":"http://media.tianxingzhe.vip/video/%E7%BE%8E%E5%9B%BD%E7%88%B1%E8%BE%BE%E8%8D%B7%E5%A4%A7%E5%AD%A6.jpg","text":"爱达荷大学","videoSrc":"http://media.tianxingzhe.vip/video/%E7%BE%8E%E5%9B%BD%E7%88%B1%E8%BE%BE%E8%8D%B7%E5%A4%A7%E5%AD%A64.mp4"},
              {"id":5,"imgSrc":"http://media.tianxingzhe.vip/video/%E7%BE%8E%E5%9B%BD%E8%80%B6%E9%B2%81%E5%A4%A7%E5%AD%A6.jpg","text":"耶鲁大学","videoSrc":"http://media.tianxingzhe.vip/video/%E7%BE%8E%E5%9B%BD%E8%80%B6%E9%B2%81%E5%A4%A7%E5%AD%A6.mp4"},
            ],
            'e':[
              {"id":1,"imgSrc":"http://media.tianxingzhe.vip/video/%E5%BE%B7%E5%9B%BD%E6%85%95%E5%B0%BC%E9%BB%91%E5%A4%A7%E5%AD%A6.jpg","text":"慕尼黑大学","videoSrc":"http://media.tianxingzhe.vip/video/%E5%BE%B7%E5%9B%BD%E6%85%95%E5%B0%BC%E9%BB%91%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":2,"imgSrc":"http://media.tianxingzhe.vip/video/%E5%BE%B7%E5%9B%BD%E6%85%95%E5%B0%BC%E9%BB%91%E5%B7%A5%E4%B8%9A%E5%A4%A7%E5%AD%A6.jpg","text":"慕尼黑工业大学","videoSrc":"http://media.tianxingzhe.vip/video/%E5%BE%B7%E5%9B%BD%E6%85%95%E5%B0%BC%E9%BB%91%E5%B7%A5%E4%B8%9A%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":3,"imgSrc":"http://media.tianxingzhe.vip/video/%E5%BE%B7%E5%9B%BD%E6%9F%8F%E6%9E%97%E5%B7%A5%E4%B8%9A%E5%A4%A7%E5%AD%A6.jpg","text":"柏林工业大学","videoSrc":"http://media.tianxingzhe.vip/video/%E5%BE%B7%E5%9B%BD%E6%9F%8F%E6%9E%97%E5%B7%A5%E4%B8%9A%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":4,"imgSrc":"http://media.tianxingzhe.vip/video/%E5%BE%B7%E5%9B%BD%E6%9F%8F%E6%9E%97%E8%87%AA%E7%94%B1%E5%A4%A7%E5%AD%A6.jpg","text":"柏林自由大学","videoSrc":"http://media.tianxingzhe.vip/video/%E5%BE%B7%E5%9B%BD%E6%9F%8F%E6%9E%97%E8%87%AA%E7%94%B1%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":5,"imgSrc":"http://media.tianxingzhe.vip/video/%E5%BE%B7%E5%9B%BD%E6%B5%B7%E5%BE%B7%E5%A0%A1%E5%A4%A7%E5%AD%A6.jpg","text":"海德堡大学","videoSrc":"http://media.tianxingzhe.vip/video/%E5%BE%B7%E5%9B%BD%E6%B5%B7%E5%BE%B7%E5%A0%A1%E5%A4%A7%E5%AD%A6.mp4"},
            ],
            'f':[
              {"id":1,"imgSrc":"http://media.tianxingzhe.vip/video/%E6%84%8F%E5%A4%A7%E5%88%A9%E4%BD%9B%E7%BD%97%E4%BC%A6%E8%90%A8%E5%A4%A7%E5%AD%A6.jpg","text":"佛罗伦萨大学","videoSrc":"http://media.tianxingzhe.vip/video/%E6%84%8F%E5%A4%A7%E5%88%A9%E4%BD%9B%E7%BD%97%E4%BC%A6%E8%90%A8%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":2,"imgSrc":"http://media.tianxingzhe.vip/video/%E6%84%8F%E5%A4%A7%E5%88%A9%E5%A8%81%E5%B0%BC%E6%96%AF%E5%A4%A7%E5%AD%A6.jpg","text":"威尼斯大学","videoSrc":"http://media.tianxingzhe.vip/video/%E6%84%8F%E5%A4%A7%E5%88%A9%E5%A8%81%E5%B0%BC%E6%96%AF%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":3,"imgSrc":"http://media.tianxingzhe.vip/video/%E6%84%8F%E5%A4%A7%E5%88%A9%E5%B8%95%E5%A4%9A%E7%93%A6%E5%A4%A7%E5%AD%A6.jpg","text":"帕多瓦大学","videoSrc":"http://media.tianxingzhe.vip/video/%E6%84%8F%E5%A4%A7%E5%88%A9%E5%B8%95%E5%A4%9A%E7%93%A6%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":4,"imgSrc":"http://media.tianxingzhe.vip/video/%E6%84%8F%E5%A4%A7%E5%88%A9%E7%B1%B3%E5%85%B0%E5%A4%A7%E5%AD%A6.jpg","text":"米兰大学","videoSrc":"http://media.tianxingzhe.vip/video/%E6%84%8F%E5%A4%A7%E5%88%A9%E7%B1%B3%E5%85%B0%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":5,"imgSrc":"http://media.tianxingzhe.vip/video/%E6%84%8F%E5%A4%A7%E5%88%A9%E7%BD%97%E9%A9%AC%E7%AC%AC%E4%B8%80%E5%A4%A7%E5%AD%A6.jpg","text":"罗马第一大学","videoSrc":"http://media.tianxingzhe.vip/video/%E6%84%8F%E5%A4%A7%E5%88%A9%E7%BD%97%E9%A9%AC%E7%AC%AC%E4%B8%80%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":6,"imgSrc":"http://media.tianxingzhe.vip/video/%E6%84%8F%E5%A4%A7%E5%88%A9%E9%83%BD%E7%81%B5%E7%90%86%E5%B7%A5%E5%A4%A7%E5%AD%A6.jpg","text":"都灵工业大学","videoSrc":"http://media.tianxingzhe.vip/video/%E6%84%8F%E5%A4%A7%E5%88%A9%E9%83%BD%E7%81%B5%E7%90%86%E5%B7%A5%E5%A4%A7%E5%AD%A6.mp4"},
            ],
            'g':[
              {"id":1,"imgSrc":"http://media.tianxingzhe.vip/video/%E6%96%B0%E5%8A%A0%E5%9D%A1%E5%8D%97%E6%B4%8B%E7%90%86%E5%B7%A5%E5%A4%A7%E5%AD%A6.jpg","text":"南洋理工大学","videoSrc":"http://media.tianxingzhe.vip/video/%E6%96%B0%E5%8A%A0%E5%9D%A1%E5%8D%97%E6%B4%8B%E7%90%86%E5%B7%A5%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":2,"imgSrc":"http://media.tianxingzhe.vip/video/%E6%96%B0%E5%8A%A0%E5%9D%A1%E5%9B%BD%E7%AB%8B%E5%A4%A7%E5%AD%A6.jpg","text":"国立大学","videoSrc":"http://media.tianxingzhe.vip/video/%E6%96%B0%E5%8A%A0%E5%9D%A1%E5%9B%BD%E7%AB%8B%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":3,"imgSrc":"http://media.tianxingzhe.vip/video/%E6%96%B0%E5%8A%A0%E5%9D%A1%E7%90%86%E5%B7%A5%E5%AD%A6%E9%99%A2.jpg","text":"理工学院","videoSrc":"http://media.tianxingzhe.vip/video/%E6%96%B0%E5%8A%A0%E5%9D%A1%E7%90%86%E5%B7%A5%E5%AD%A6%E9%99%A2.mp4"},
              {"id":4,"imgSrc":"http://media.tianxingzhe.vip/video/%E6%96%B0%E5%8A%A0%E5%9D%A1%E7%AE%A1%E7%90%86%E5%A4%A7%E5%AD%A6.jpg","text":"管理大学","videoSrc":"http://media.tianxingzhe.vip/video/%E6%96%B0%E5%8A%A0%E5%9D%A1%E7%AE%A1%E7%90%86%E5%A4%A7%E5%AD%A6.mp4"},
            ],
            'h':[
              {"id":1,"imgSrc":"http://media.tianxingzhe.vip/video/%E6%96%B0%E8%A5%BF%E5%85%B0%E5%9C%A3%E7%BB%8F%E5%AD%A6%E9%99%A2.jpg","text":"圣经学院","videoSrc":"http://media.tianxingzhe.vip/video/%E6%96%B0%E8%A5%BF%E5%85%B0%E5%9C%A3%E7%BB%8F%E5%AD%A6%E9%99%A2.mp4"},
              {"id":2,"imgSrc":"http://media.tianxingzhe.vip/video/%E6%96%B0%E8%A5%BF%E5%85%B0%E5%A5%A5%E5%85%8B%E5%85%B0%E5%A4%A7%E5%AD%A6.jpg","text":"奥克兰大学","videoSrc":"http://media.tianxingzhe.vip/video/%E6%96%B0%E8%A5%BF%E5%85%B0%E5%A5%A5%E5%85%8B%E5%85%B0%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":3,"imgSrc":"http://media.tianxingzhe.vip/video/%E6%96%B0%E8%A5%BF%E5%85%B0%E6%80%80%E5%8D%A1%E6%89%98%E5%A4%A7%E5%AD%A6.jpg","text":"奥克兰理工大学","videoSrc":"http://media.tianxingzhe.vip/video/%E6%96%B0%E8%A5%BF%E5%85%B0%E5%A5%A5%E5%85%8B%E5%85%B0%E7%90%86%E5%B7%A5%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":4,"imgSrc":"http://media.tianxingzhe.vip/video/%E6%96%B0%E8%A5%BF%E5%85%B0%E8%81%94%E5%90%88%E7%90%86%E5%B7%A5%E5%AD%A6%E9%99%A2.jpg","text":"怀卡托大学","videoSrc":"http://media.tianxingzhe.vip/video/%E6%96%B0%E8%A5%BF%E5%85%B0%E6%80%80%E5%8D%A1%E6%89%98%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":5,"imgSrc":"http://media.tianxingzhe.vip/video/%E6%96%B0%E8%A5%BF%E5%85%B0%E8%81%94%E5%90%88%E7%90%86%E5%B7%A5%E5%AD%A6%E9%99%A2.jpg","text":"联合理工学院","videoSrc":"http://media.tianxingzhe.vip/video/%E6%96%B0%E8%A5%BF%E5%85%B0%E8%81%94%E5%90%88%E7%90%86%E5%B7%A5%E5%AD%A6%E9%99%A2.mp4"},
            ],
            'i':[
              {"id":1,"imgSrc":"http://media.tianxingzhe.vip/video/%E6%BE%B3%E5%A4%A7%E5%88%A9%E4%BA%9A%E5%9B%BD%E7%AB%8B%E5%A4%A7%E5%AD%A6.jpg","text":"澳大利亚国立大学","videoSrc":"http://media.tianxingzhe.vip/video/%E6%BE%B3%E5%A4%A7%E5%88%A9%E4%BA%9A%E5%9B%BD%E7%AB%8B%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":2,"imgSrc":"http://media.tianxingzhe.vip/video/%E6%BE%B3%E5%A4%A7%E5%88%A9%E4%BA%9A%E5%A2%A8%E5%B0%94%E6%9C%AC%E5%A4%A7%E5%AD%A6.jpg","text":"墨尔本大学","videoSrc":"http://media.tianxingzhe.vip/video/%E6%BE%B3%E6%B4%B2%E5%A2%A8%E5%B0%94%E6%9C%AC%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":3,"imgSrc":"http://media.tianxingzhe.vip/video/%E6%BE%B3%E5%A4%A7%E5%88%A9%E4%BA%9A%E6%82%89%E5%B0%BC%E5%A4%A7%E5%AD%A6.jpg","text":"悉尼大学","videoSrc":"http://media.tianxingzhe.vip/video/%E6%BE%B3%E6%B4%B2%E6%82%89%E5%B0%BC%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":4,"imgSrc":"http://media.tianxingzhe.vip/video/%E6%BE%B3%E5%A4%A7%E5%88%A9%E4%BA%9A%E6%96%B0%E5%8D%97%E5%A8%81%E5%B0%94%E5%A3%AB%E5%A4%A7%E5%AD%A6.jpg","text":"新南威尔士大学","videoSrc":"http://media.tianxingzhe.vip/video/%E6%BE%B3%E6%B4%B2%E6%96%B0%E5%8D%97%E5%A8%81%E5%B0%94%E5%A3%AB%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":5,"imgSrc":"http://media.tianxingzhe.vip/video/%E6%BE%B3%E5%A4%A7%E5%88%A9%E4%BA%9A%E8%8E%AB%E7%BA%B3%E4%BB%80%E5%A4%A7%E5%AD%A6.jpg","text":"莫纳什大学","videoSrc":"http://media.tianxingzhe.vip/video/%E6%BE%B3%E6%B4%B2%E8%8E%AB%E7%BA%B3%E4%BB%80%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":6,"imgSrc":"http://media.tianxingzhe.vip/video/%E6%BE%B3%E5%A4%A7%E5%88%A9%E4%BA%9A%E9%98%BF%E5%BE%B7%E8%8E%B1%E5%BE%B7%E5%A4%A7%E5%AD%A6.jpg","text":"阿德莱德大学","videoSrc":"http://media.tianxingzhe.vip/video/%E6%BE%B3%E6%B4%B2%E9%98%BF%E5%BE%B7%E8%8E%B1%E5%BE%B7%E5%A4%A7%E5%AD%A6.mp4"},
            ],
            'j':[
              {"id":1,"imgSrc":"http://media.tianxingzhe.vip/video/%E8%A5%BF%E7%8F%AD%E7%89%99%E5%8A%A0%E6%B3%B0%E7%BD%97%E5%B0%BC%E8%A5%BF%E4%BA%9A%E7%90%86%E5%B7%A5%E5%A4%A7%E5%AD%A6.jpg","text":"加泰罗尼西亚大学","videoSrc":"http://media.tianxingzhe.vip/video/%E8%A5%BF%E7%8F%AD%E7%89%99%E5%8A%A0%E6%B3%B0%E7%BD%97%E5%B0%BC%E8%A5%BF%E4%BA%9A%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":2,"imgSrc":"http://media.tianxingzhe.vip/video/%E8%A5%BF%E7%8F%AD%E7%89%99%E5%B7%B4%E5%A1%9E%E7%BD%97%E9%82%A3%E5%A4%A7%E5%AD%A6.jpg","text":"巴塞罗那大学","videoSrc":"http://media.tianxingzhe.vip/video/%E8%A5%BF%E7%8F%AD%E7%89%99%E5%B7%B4%E5%A1%9E%E7%BD%97%E9%82%A3%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":3,"imgSrc":"http://media.tianxingzhe.vip/video/%E8%A5%BF%E7%8F%AD%E7%89%99%E5%B7%B4%E6%96%AF%E5%85%8B%E5%A4%A7%E5%AD%A6.jpg","text":"巴斯克大学","videoSrc":"http://media.tianxingzhe.vip/video/%E8%A5%BF%E7%8F%AD%E7%89%99%E5%B7%B4%E6%96%AF%E5%85%8B%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":4,"imgSrc":"http://media.tianxingzhe.vip/video/%E8%A5%BF%E7%8F%AD%E7%89%99%E7%93%A6%E4%BC%A6%E8%A5%BF%E4%BA%9A%E5%A4%A7%E5%AD%A6.jpg","text":"瓦伦西亚大学","videoSrc":"http://media.tianxingzhe.vip/video/%E8%A5%BF%E7%8F%AD%E7%89%99%E7%93%A6%E4%BC%A6%E8%A5%BF%E4%BA%9A%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":5,"imgSrc":"http://media.tianxingzhe.vip/video/%E8%A5%BF%E7%8F%AD%E7%89%99%E8%90%A8%E6%8B%89%E6%9B%BC%E5%8D%A1%E5%A4%A7%E5%AD%A6.jpg","text":"萨拉曼卡大学","videoSrc":"http://media.tianxingzhe.vip/video/%E8%A5%BF%E7%8F%AD%E7%89%99%E8%90%A8%E6%8B%89%E6%9B%BC%E5%8D%A1%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":6,"imgSrc":"http://media.tianxingzhe.vip/video/%E8%A5%BF%E7%8F%AD%E7%89%99%E9%98%BF%E5%B0%94%E5%8D%A1%E6%8B%89%E5%A4%A7%E5%AD%A6.jpg","text":"阿尔卡拉大学","videoSrc":"http://media.tianxingzhe.vip/video/%E8%A5%BF%E7%8F%AD%E7%89%99%E9%98%BF%E5%B0%94%E5%8D%A1%E6%8B%89%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":7,"imgSrc":"http://media.tianxingzhe.vip/video/%E8%A5%BF%E7%8F%AD%E7%89%99%E9%A9%AC%E5%BE%B7%E9%87%8C%E7%90%86%E5%B7%A5%E5%A4%A7%E5%AD%A6.jpg","text":"马德里理工大学","videoSrc":"http://media.tianxingzhe.vip/video/%E8%A5%BF%E7%8F%AD%E7%89%99%E9%A9%AC%E5%BE%B7%E9%87%8C%E7%90%86%E5%B7%A5%E5%A4%A7%E5%AD%A6.mp4"},
            ],
            'k':[
              {"id":1,"imgSrc":"http://media.tianxingzhe.vip/video/%E9%A6%99%E6%B8%AF%E4%B8%AD%E6%96%87%E5%A4%A7%E5%AD%A6.jpg","text":"香港中文大学","videoSrc":"http://media.tianxingzhe.vip/video/%E9%A6%99%E6%B8%AF%E4%B8%AD%E6%96%87%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":2,"imgSrc":"http://media.tianxingzhe.vip/video/%E9%A6%99%E6%B8%AF%E5%9F%8E%E5%B8%82%E5%A4%A7%E5%AD%A6.jpg","text":"城市大学","videoSrc":"http://media.tianxingzhe.vip/video/%E9%A6%99%E6%B8%AF%E5%9F%8E%E5%B8%82%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":3,"imgSrc":"http://media.tianxingzhe.vip/video/%E9%A6%99%E6%B8%AF%E5%A4%A7%E5%AD%A6.jpg","text":"香港大学","videoSrc":"http://media.tianxingzhe.vip/video/%E9%A6%99%E6%B8%AF%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":4,"imgSrc":"http://media.tianxingzhe.vip/video/%E9%A6%99%E6%B8%AF%E6%B5%B8%E4%BC%9A%E5%A4%A7%E5%AD%A6.jpg","text":"浸会大学","videoSrc":"http://media.tianxingzhe.vip/video/%E9%A6%99%E6%B8%AF%E6%B5%B8%E4%BC%9A%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":5,"imgSrc":"http://media.tianxingzhe.vip/video/%E9%A6%99%E6%B8%AF%E7%A7%91%E6%8A%80%E5%A4%A7%E5%AD%A6.jpg","text":"科技大学","videoSrc":"http://media.tianxingzhe.vip/video/%E9%A6%99%E6%B8%AF%E7%A7%91%E6%8A%80%E5%A4%A7%E5%AD%A6.mp4"},
            ],
            'l':[
              {"id":1,"imgSrc":"http://media.tianxingzhe.vip/video/%E8%8D%B7%E5%85%B0%E8%8E%B1%E9%A1%BF%E5%A4%A7%E5%AD%A6.jpg","text":"莱顿大学","videoSrc":"http://media.tianxingzhe.vip/video/%E8%8D%B7%E5%85%B0%E8%8E%B1%E9%A1%BF%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":2,"imgSrc":"http://media.tianxingzhe.vip/video/%E8%8D%B7%E5%85%B0%E9%98%BF%E5%A7%86%E6%96%AF%E7%89%B9%E4%B8%B9%E5%A4%A7%E5%AD%A6.jpg","text":"阿姆斯特丹大学","videoSrc":"http://media.tianxingzhe.vip/video/%E8%8D%B7%E5%85%B0%E9%98%BF%E5%A7%86%E6%96%AF%E7%89%B9%E4%B8%B9%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":3,"imgSrc":"http://media.tianxingzhe.vip/video/%E8%8D%B7%E5%85%B0%E9%A9%AC%E6%96%AF%E7%89%B9%E9%87%8C%E8%B5%AB%E7%89%B9%E5%A4%A7%E5%AD%A6.jpg","text":"阿姆斯特丹自由大学","videoSrc":"http://media.tianxingzhe.vip/video/%E8%8D%B7%E5%85%B0%E9%98%BF%E5%A7%86%E6%96%AF%E7%89%B9%E4%B8%B9%E8%87%AA%E7%94%B1%E5%A4%A7%E5%AD%A6.mp4"},
              {"id":4,"imgSrc":"http://media.tianxingzhe.vip/video/%E8%8D%B7%E5%85%B0%E9%A9%AC%E6%96%AF%E7%89%B9%E9%87%8C%E8%B5%AB%E7%89%B9%E5%A4%A7%E5%AD%A6.jpg","text":"马斯特里赫特大学","videoSrc":"http://media.tianxingzhe.vip/video/%E8%8D%B7%E5%85%B0%E9%A9%AC%E6%96%AF%E7%89%B9%E9%87%8C%E8%B5%AB%E7%89%B9%E5%A4%A7%E5%AD%A6.mp4"},
             ],

        }
    },
    "info":{
        "resultList1":[
            {"title":"推荐信"},{"title":"学习计划"},{"title":"个人简历"},{"title":"成绩单"},
            {"title":"选校报告"},{"title":"语言证明"},{"title":"面试辅导"},{"title":"在读证明"},
            {"title":"获奖证明"},{"title":"作品集"},{"title":"毕业证书"},{"title":"录取信"},
            {"title":"签证清单"},{"title":"资金证明"},{"title":"签证信息表"},{"title":"签证方案"},
            {"title":"工作收入证明"},{"title":"面签辅导"},{"title":"照片"},{"title":"翻译件"},
            {"title":"不动产证明"},{"title":"护照"},{"title":"户口本"},{"title":"身份证"},
            {"title":"出国保单"},{"title":"行前辅导"},
          ],
    },
}